name: egm722_NDVI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - geopandas
  - rasterio
  - shapely
  - geopy
  - pyproj
  - numpy
  - matplotlib
  - pip
  - pip:
    - cdsetool